#
# Kubernetes API Permissions
#
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: cluster-ingress-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: cluster-ingress-controller
---
#
# Deployment
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: ingress-controller
  labels:
    app: ingress-controller
spec:
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
        name: ingress-controller
    spec:
      serviceAccountName: cluster-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
        - image: traefik
          name: ingress-controller
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: admin
              containerPort: 8080
              hostPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --api.insecure
            - --accesslog
            - --providers.kubernetesingress
            - --log
            - --log.level=INFO
---
#
# External Load Balancer
#
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: ingress-controller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 8080
      name: http-admin
  selector:
    app: ingress-controller
